# Generated by Django 3.2.24 on 2024-03-15 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='posts/media'),
            preserve_default=False,
        ),
    ]
