# Generated by Django 3.2.23 on 2024-03-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240323_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlikes',
            options={'ordering': ['-created_at']},
        ),
    ]
