# Generated by Django 3.2.23 on 2024-03-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_status'),
        ('posts', '0007_auto_20240319_1125'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('post', 'user')},
        ),
    ]
