# Generated by Django 3.2.23 on 2024-03-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_status'),
        ('posts', '0008_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userposts', to='profiles.userprofile'),
        ),
    ]
