# Generated by Django 3.2.23 on 2024-03-31 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last Seen'),
            preserve_default=False,
        ),
    ]
