# Generated by Django 3.2.23 on 2024-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240317_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
