# Generated by Django 3.2.23 on 2024-03-17 11:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'followed')},
        ),
    ]
