# Generated by Django 3.2.23 on 2024-03-30 03:05

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usera_last_seen', models.DateTimeField(blank=True, null=True, verbose_name='UserA Last seen')),
                ('userb_last_seen', models.DateTimeField(blank=True, null=True, verbose_name='UserB Last seen')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Last Changes')),
                ('usera_read', models.BooleanField(default=False, verbose_name='Do User A have latest updates')),
                ('userb_read', models.BooleanField(default=False, verbose_name='Do User B have latest updates')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_person', to='profiles.userprofile', verbose_name='User A')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver_person', to='profiles.userprofile', verbose_name='User A')),
            ],
            options={
                'ordering': ['-last_update'],
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='User Message')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('video', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='post_images/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Is Viewed')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermessages.userchat', verbose_name='Chat Node')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reciever', to='profiles.userprofile', verbose_name='Reciever')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='profiles.userprofile', verbose_name='Sender')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
