# Generated by Django 3.2.23 on 2024-03-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchat',
            name='usera_read',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='userb_read',
        ),
    ]
