# Generated by Django 3.2.23 on 2024-03-31 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0002_auto_20240330_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ['created']},
        ),
    ]
